### ISSUE TITLE
Path with space not supported

### ISSUE THREAD

**Issue by chaoscreater** [nkn-ms/vscode-cd-to-active-file-directory#1]
Hi there, I came across your VS Code extension. 

If there's a space in the path, this doesn't CD to the path. I think it just needs to be enclosed with quotes to work. Could you please update this to support spaces in path please?

**Comment by nkn-ms** [comment]
Hi, thank you for letting me know.
I'll try to fix as soon as possible.
But, if you don't mind, could you tell me the error case path.
I thought it was handled by under code

https://github.com/nkn-ms/vscode-cd-to-active-file-directory/blob/e977351cb6b1756b15c9af7bb6807f9f059eacbc/src/extension.ts#L35-L37

I trust what you said, but I don't know error path pattern.
If you tell me it, I'll fix it rapidly.

**Comment by chaoscreater** [comment]
Hi, thanks for looking into this. Here's the error:

![image](https://github.com/nkn-ms/vscode-cd-to-active-file-directory/assets/18227319/38ffec0d-23ae-4eb1-8f6f-f8752b3a9a4f)

The path is:
D:\Documents\0. My Stuffs\1. Work\1. My work companies\test company\New Text Document.txt

but the path generated by your extension is incorrect. It shows this instead:
D:\Documents\0. \ My\ Stuffs\1. Work\1. \ My\ work\ companies\test\ company\New\ Text

**Comment by nkn-ms** [comment]
Thank you for your prompt reply.
I understood the reason.
That is derived from windows system, I thought only linux system.
It may take some time, I'll try it.

**Comment by chaoscreater** [comment]
I've just tried out the latest update and it works! Thank you very much <3

**Comment by nkn-ms** [comment]
@chaoscreater 
I've learned a lot. Thank you.
